import type {Address, ClientVpnEndpoint, DhcpOptions, Ec2InstanceConnectEndpoint, EgressOnlyInternetGateway, FleetData, FlowLog, Image, ImageRecycleBinInfo, Instance, InternetGateway, KeyPairInfo, LaunchTemplate, LocalGateway, LocalGatewayRouteTable, LocalGatewayRouteTableVpcAssociation, LocalGatewayVirtualInterface, LocalGatewayVirtualInterfaceGroup, ManagedPrefixList, NatGateway, NetworkAcl, NetworkInterface, Region, RouteTable, SecurityGroup, SecurityGroupRule, ServiceConfiguration, Snapshot, SnapshotRecycleBinInfo, StaleSecurityGroup, Subnet, TrafficMirrorFilter, TrafficMirrorSession, TrafficMirrorTarget, TransitGateway, TransitGatewayAttachment, TransitGatewayConnect, TransitGatewayConnectPeer, TransitGatewayPeeringAttachment, TransitGatewayRouteTable, TransitGatewayVpcAttachment, VerifiedAccessEndpoint, VerifiedAccessGroup, VerifiedAccessInstance, VerifiedAccessTrustProvider, Volume, Vpc, VpcEndpoint, VpcPeeringConnection} from "@aws-sdk/client-ec2";

export interface Ec2 {
    getEnabledRegions(): Promise<Region[]>;
    getVpcs(): Promise<Vpc[]>;
    getSubnets(): Promise<Subnet[]>;
    getSecurityGroups(): Promise<SecurityGroup[]>;
    getInternetGateways(): Promise<InternetGateway[]>;
    getNatGateways(): Promise<NatGateway[]>;
    getEgressOnlyInternetGateways(): Promise<EgressOnlyInternetGateway[]>;
    getNetworkInterfaces (): Promise<NetworkInterface[]>;
    getRouteTables (): Promise<RouteTable[]>;
    getVolumes (): Promise<Volume[]>;
    getInstances (): Promise<Instance[]>;
    getVpcEndpoints (): Promise<VpcEndpoint[]>;
    getAddresses (): Promise<Address[]>;
    getImages (): Promise<Image[]>;
    getSnapshots (): Promise<Snapshot[]>;
    getKeyPairs (): Promise<KeyPairInfo[]>;
    getNetworkAcls (): Promise<NetworkAcl[]>;
    getFlowLogs (): Promise<FlowLog[]>;
    getDhcpOptions (): Promise<DhcpOptions[]>;
    getManagedPrefixLists (): Promise<ManagedPrefixList[]>;
    getVpcPeeringConnections (): Promise<VpcPeeringConnection[]>;
    getLaunchTemplates (): Promise<LaunchTemplate[]>;
    getTransitGateways (): Promise<TransitGateway[]>;
    getTransitGatewayAttachments (): Promise<TransitGatewayAttachment[]>;
    getTransitGatewayRouteTables (): Promise<TransitGatewayRouteTable[]>;
    getSecurityGroupRules (): Promise<SecurityGroupRule[]>;
    getLocalGateways (): Promise<LocalGateway[]>;
    getLocalGatewayRouteTables (): Promise<LocalGatewayRouteTable[]>;
    getLocalGatewayRouteTableVpcAssociations (): Promise<LocalGatewayRouteTableVpcAssociation[]>;
    getLocalGatewayVirtualInterfaces (): Promise<LocalGatewayVirtualInterface[]>;
    getLocalGatewayVirtualInterfaceGroups (): Promise<LocalGatewayVirtualInterfaceGroup[]>;
    getStaleSecurityGroups (vpcId: string): Promise<StaleSecurityGroup[]>;
    getInstanceConnectEndpoints (): Promise<Ec2InstanceConnectEndpoint[]>;
    getImagesInRecycleBin (): Promise<ImageRecycleBinInfo[]>;
    getSnapshotsInRecycleBin (): Promise<SnapshotRecycleBinInfo[]>;
    getFleets (): Promise<FleetData[]>;
    getTrafficMirrorSessions (): Promise<TrafficMirrorSession[]>;
    getTrafficMirrorTargets (): Promise<TrafficMirrorTarget[]>;
    getTrafficMirrorFilters (): Promise<TrafficMirrorFilter[]>;
    getClientVpnEndpoints (): Promise<ClientVpnEndpoint[]>;
    getTransitGatewayVpcAttachments (): Promise<TransitGatewayVpcAttachment[]>;
    getTransitGatewayPeeringAttachments (): Promise<TransitGatewayPeeringAttachment[]>;
    getTransitGatewayConnects (): Promise<TransitGatewayConnect[]>;
    getTransitGatewayConnectPeers (): Promise<TransitGatewayConnectPeer[]>;
    getVerifiedAccessInstances (): Promise<VerifiedAccessInstance[]>;
    getVerifiedAccessGroups (): Promise<VerifiedAccessGroup[]>;
    getVerifiedAccessEndpoints (): Promise<VerifiedAccessEndpoint[]>;
    getVerifiedAccessTrustProviders (): Promise<VerifiedAccessTrustProvider[]>;
    getVpcEndpointServiceConfigurations (): Promise<ServiceConfiguration[]>;
}
