import type {AwsCredentialIdentityProvider, AwsCredentialIdentity} from "@aws-sdk/types";
import type {Account} from "./interfaces/account.js";
import type {Ec2} from "./interfaces/ec2.js";
import type {Iam} from "./interfaces/iam.js";
import type {Lambda} from "./interfaces/lambda.js";
import type {S3} from "./interfaces/s3.js";
import type {S3Tables} from "./interfaces/s3tables.js";
import type {CloudWatch} from "./interfaces/cloudwatch.js";
import type {CloudFront} from "./interfaces/cloudfront.js";
import type {DynamoDB} from "./interfaces/dynamodb.js";
import type {Ebs} from "./interfaces/ebs.js";
import type {Ecr} from "./interfaces/ecr.js";
import type {Ecs} from "./interfaces/ecs.js";
import type {Elbv2} from "./interfaces/elbv2.js";
import type {Sns} from "./interfaces/sns.js";
import type {Sqs} from "./interfaces/sqs.js";
import type {Route53} from "./interfaces/route53.js";
import type {Eks} from "./interfaces/eks.js";
import type {SecretsManager} from "./interfaces/secretsmanager.js";
import type {Acm} from "./interfaces/acm.js";
import type {Efs} from "./interfaces/efs.js";
import type {Kms} from "./interfaces/kms.js";
import type {AutoScaling} from "./interfaces/autoscaling.js";
import type {Rds} from "./interfaces/rds.js";
import type {ApiGateway} from "./interfaces/apigateway.js";
import type {Waf} from "./interfaces/waf.js";
import type {ElastiCache} from "./interfaces/elasticache.js";
import type {EventBridge} from "./interfaces/eventbridge.js";
import type {Organizations} from "./interfaces/organizations.js";
import type {Sfn} from "./interfaces/sfn.js";
import type {Kinesis} from "./interfaces/kinesis.js";
import type {OpenSearch} from "./interfaces/opensearch.js";
import type {CodeBuild} from "./interfaces/codebuild.js";
import type {Cognito} from "./interfaces/cognito.js";
import type {ServiceDiscovery} from "./interfaces/servicediscovery.js";
import type {Backup} from "./interfaces/backup.js";
import type {Glacier} from "./interfaces/glacier.js";
import type {CodeArtifact} from "./interfaces/codeartifact.js";
import type {Msk} from "./interfaces/msk.js";
import type {Redshift} from "./interfaces/redshift.js";
import type {Neptune} from "./interfaces/neptune.js";
import type {DocDb} from "./interfaces/docdb.js";
import type {Fsx} from "./interfaces/fsx.js";
import type {NetworkFirewall} from "./interfaces/networkfirewall.js";
import type {CodePipeline} from "./interfaces/codepipeline.js";
import type {CloudTrail} from "./interfaces/cloudtrail.js";
import type {GlobalAcceleratorService} from "./interfaces/globalaccelerator.js";
import type {Ssm} from "./interfaces/ssm.js";
import type {CloudFormation} from "./interfaces/cloudformation.js";
import type {Mq} from "./interfaces/mq.js";
import type {Mwaa} from "./interfaces/mwaa.js";
import type {AppRunner} from "./interfaces/apprunner.js";
import type {Transfer} from "./interfaces/transfer.js";
import type {VpcLattice} from "./interfaces/vpclattice.js";
import type {NetworkManager} from "./interfaces/networkmanager.js";
import type {Iot} from "./interfaces/iot.js";
import type {DataSync} from "./interfaces/datasync.js";
import type {AppSync} from "./interfaces/appsync.js";
import type {RedshiftServerless} from "./interfaces/redshiftserverless.js";
import type {OpenSearchServerless} from "./interfaces/opensearchserverless.js";
import type {DirectoryService} from "./interfaces/directoryservice.js";
import type {WorkSpaces} from "./interfaces/workspaces.js";
import type {CloudHsm} from "./interfaces/cloudhsm.js";
import type {AppMesh} from "./interfaces/appmesh.js";
import type {S3Control} from "./interfaces/s3control.js";
import type {Elb} from "./interfaces/elb.js";
import type {Pipes} from "./interfaces/pipes.js";
import type {StorageGateway} from "./interfaces/storagegateway.js";
import type {Outposts} from "./interfaces/outposts.js";
import type {ImageBuilder} from "./interfaces/imagebuilder.js";
import type {CodeDeploy} from "./interfaces/codedeploy.js";
import type {MediaConnect} from "./interfaces/mediaconnect.js";
import type {SageMaker} from "./interfaces/sagemaker.js";
import type {Glue} from "./interfaces/glue.js";
import type {Dms} from "./interfaces/dms.js";
import type {Route53Resolver} from "./interfaces/route53resolver.js";
import type {Batch} from "./interfaces/batch.js";
import type {MemoryDb} from "./interfaces/memorydb.js";
import type {Emr} from "./interfaces/emr.js";
import type {EmrServerless} from "./interfaces/emrserverless.js";
import type {ElasticBeanstalk} from "./interfaces/elasticbeanstalk.js";
import type {Athena} from "./interfaces/athena.js";

export abstract class ServiceFactory {

    abstract createAccountService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity): Account;
    abstract createEc2Service (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Ec2;
    abstract createIamService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity): Iam;
    abstract createLambdaService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Lambda;
    abstract createS3Service (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity): S3;
    abstract createS3TablesService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): S3Tables;
    abstract createDynamoDBService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): DynamoDB;
    abstract createEbsService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Ebs;
    abstract createEcrService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Ecr;
    abstract createEcsService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Ecs;
    abstract createElbv2Service (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Elbv2;
    abstract createSnsService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Sns;
    abstract createSqsService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Sqs;
    abstract createRoute53Service (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity): Route53;
    abstract createEksService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Eks;
    abstract createSecretsManagerService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): SecretsManager;
    abstract createCloudWatchService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): CloudWatch;
    abstract createCloudFrontService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity): CloudFront;
    abstract createAcmService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Acm;
    abstract createEfsService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Efs;
    abstract createKmsService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Kms;
    abstract createAutoScalingService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): AutoScaling;
    abstract createRdsService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Rds;
    abstract createApiGatewayService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): ApiGateway;
    abstract createWafService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Waf;
    abstract createElastiCacheService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): ElastiCache;
    abstract createEventBridgeService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): EventBridge;
    abstract createOrganizationsService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity): Organizations;
    abstract createSfnService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Sfn;
    abstract createKinesisService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Kinesis;
    abstract createOpenSearchService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): OpenSearch;
    abstract createCodeBuildService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): CodeBuild;
    abstract createCognitoService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Cognito;
    abstract createServiceDiscoveryService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): ServiceDiscovery;
    abstract createBackupService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Backup;
    abstract createGlacierService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Glacier;
    abstract createCodeArtifactService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): CodeArtifact;
    abstract createMskService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Msk;
    abstract createRedshiftService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Redshift;
    abstract createNeptuneService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Neptune;
    abstract createDocDbService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): DocDb;
    abstract createFsxService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Fsx;
    abstract createNetworkFirewallService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): NetworkFirewall;
    abstract createCodePipelineService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): CodePipeline;
    abstract createCloudTrailService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): CloudTrail;
    abstract createGlobalAcceleratorService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity): GlobalAcceleratorService;
    abstract createSsmService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Ssm;
    abstract createCloudFormationService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): CloudFormation;
    abstract createMqService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Mq;
    abstract createMwaaService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Mwaa;
    abstract createAppRunnerService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): AppRunner;
    abstract createTransferService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Transfer;
    abstract createVpcLatticeService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): VpcLattice;
    abstract createNetworkManagerService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): NetworkManager;
    abstract createIotService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Iot;
    abstract createGlueService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Glue;
    abstract createDmsService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Dms;
    abstract createRoute53ResolverService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Route53Resolver;
    abstract createBatchService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Batch;
    abstract createMemoryDbService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): MemoryDb;
    abstract createEmrService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Emr;
    abstract createEmrServerlessService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): EmrServerless;
    abstract createElasticBeanstalkService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): ElasticBeanstalk;
    abstract createAthenaService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Athena;
    abstract createDataSyncService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): DataSync;
    abstract createAppSyncService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): AppSync;
    abstract createRedshiftServerlessService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): RedshiftServerless;
    abstract createOpenSearchServerlessService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): OpenSearchServerless;
    abstract createDirectoryServiceService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): DirectoryService;
    abstract createWorkspacesService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): WorkSpaces;
    abstract createCloudHsmService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): CloudHsm;
    abstract createAppMeshService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): AppMesh;
    abstract createS3ControlService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string, accountId: string): S3Control;
    abstract createElbService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Elb;
    abstract createPipesService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Pipes;
    abstract createStorageGatewayService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): StorageGateway;
    abstract createOutpostsService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): Outposts;
    abstract createImageBuilderService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): ImageBuilder;
    abstract createCodeDeployService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): CodeDeploy;
    abstract createMediaConnectService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): MediaConnect;
    abstract createSageMakerService (credentials: AwsCredentialIdentityProvider | AwsCredentialIdentity, region: string): SageMaker;

}
